### ISSUE TITLE
关于配置里这些的对应的属性的疑惑

### ISSUE THREAD

**Issue by humucai** [abel533/MyBatis-Spring-Boot#73]
Hi ，请问下面 mapper.mappers 下面MyMapper的作用的使用，
示例代码中此接口只是直接继承一个Mapper
文档中也并没找到这些配置对应的属性的说明。

```
mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

```
