### ISSUE TITLE
spring boot 对mapper的扫描是怎么定义的

### ISSUE THREAD

**Issue by qq1026290752** [abel533/MyBatis-Spring-Boot#80]
今天在整合的时候 出现以下错误
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in com.manong.boot.service.user.impl.UserServiceImpl required a bean of type 'com.manong.boot.mapper.UserMapper' that could not be found.


Action:

Consider defining a bean of type 'com.manong.boot.mapper.UserMapper' in your configuration.

```
个人配置：
```
## 整合通用mapper
mapper:
    mappers:
       - com.manong.boot.mapper.GenericMapper
    not-empty: false
    identity: MYSQL
```
